name: hourly-taxi-demand-inference-pipeline

on:
  workflow_run:
    workflows: ["hourly-taxi-demand-feature-pipeline"]
    types:
      - completed

  workflow_dispatch:

env:
  PYTHON_VERSION: 3.9
  POETRY_VERSION: 1.4.2
  POETRY_URL: https://install.python-poetry.org

jobs:

  inference_pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Cache Poetry cache
      uses: actions/cache@v3

      with:
        path: ~/.cache/pypoetry
        key: poetry-cache-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ env.POETRY_VERSION }}

    - name: Cache Packages
      uses: actions/cache@v3
      with:
        path: ~/.local
        key: poetry-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('.github/workflows/*.yml') }}
    
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install Poetry
      run: |
        curl -sSL ${{ env.POETRY_URL }} | python - --version ${{ env.POETRY_VERSION }}
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    
    - name: Install Dependencies
      with: 
        max_attemps: 3
      run: poetry install

    - name: execute python workflows from bash script
      with: 
        max_attemps: 3

      env:
        HOPSWORKSAPIKEY: ${{ secrets.HOPSWORKSAPIKEY }}
      run: poetry run jupyter nbconvert --to notebook --execute notebooks/InferencePipeline.ipynb


